userYamlEntries:
 - username: Dominic
   password: 123
   phoneNr: 0041791234567
   roles:
     - USER
 - username: Hans
   password: 321
   phoneNr: 0001234567
   roles:
     - USER
 - username: Peter
   password: 321
   phoneNr: 0001234569
   roles:
     - USER
 - username: Heinz
   password: 3210
   phoneNr: 0001234580
   roles:
     - USER